"""
Parse TMDL files to extract measure definitions.

Handles three measure syntax variants:
  1. Single-line:    measure 'Name' = DAX_EXPRESSION
  2. Multi-line:     measure 'Name' =\\n\\t\\tLINE1\\n\\t\\tLINE2  (no backticks)
  3. Code block:     measure 'Name' = ```\\n\\t\\tDAX\\n\\t\\t```
"""

import re
from dataclasses import dataclass
from pathlib import Path


@dataclass
class MeasureInfo:
    name: str
    table: str
    expression: str
    format_string: str = None
    is_hidden: bool = False
    file_path: str = ""


# Files to skip — auto-generated by Power BI, contain no user measures
_SKIP_PREFIXES = ("LocalDateTable_", "DateTableTemplate_")

# Regex for the measure declaration line
_MEASURE_RE = re.compile(
    r"^\tmeasure\s+'([^']+)'\s*=\s*(.*)$"
    r"|"
    r"^\tmeasure\s+(\S+)\s*=\s*(.*)$"
)

# Keywords that signal end of a measure's DAX expression
_END_KEYWORDS = (
    "lineageTag:", "formatString:", "annotation ", "changedProperty",
    "measure ", "column ", "partition ", "table ", "expression ",
    "hierarchy ", "relationship ",
)


def _parse_table_name(lines):
    """Extract the table name from the first line of a TMDL file."""
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("table "):
            # table 'Name With Spaces' or table SimpleName
            rest = stripped[6:].strip()
            if rest.startswith("'"):
                # Find closing quote
                end = rest.find("'", 1)
                if end > 0:
                    return rest[1:end]
            return rest.split()[0] if rest else ""
    return ""


def _parse_measures(lines, table_name, file_path):
    """Parse all measures from TMDL file lines."""
    measures = []
    i = 0

    while i < len(lines):
        line = lines[i]
        m = _MEASURE_RE.match(line)
        if not m:
            i += 1
            continue

        # Extract measure name
        name = m.group(1) or m.group(3)
        remainder = (m.group(2) or m.group(4) or "").strip()

        # Parse the DAX expression
        expression_lines = []
        is_hidden = False
        format_string = None

        if remainder.startswith("```"):
            # Code block variant — read until closing ```
            # The remainder after ``` on the same line (if any)
            after_backtick = remainder[3:].strip()
            if after_backtick:
                expression_lines.append(after_backtick)

            i += 1
            while i < len(lines):
                l = lines[i].strip()
                if l == "```" or l.endswith("```"):
                    # Closing backtick — include content before it if any
                    before = l[:-3].strip()
                    if before:
                        expression_lines.append(before)
                    i += 1
                    break
                expression_lines.append(lines[i].strip())
                i += 1

        elif remainder:
            # Single-line variant — expression is the remainder
            expression_lines.append(remainder)
            i += 1

        else:
            # Multi-line variant (no backticks) — read indented lines
            i += 1
            while i < len(lines):
                l = lines[i]
                stripped = l.strip()
                # Check if this line is a metadata keyword (end of expression)
                if any(stripped.startswith(kw) for kw in _END_KEYWORDS):
                    break
                if stripped == "":
                    # Blank lines within expression are OK
                    expression_lines.append("")
                    i += 1
                    continue
                # Must be indented (part of expression)
                if l.startswith("\t\t") or l.startswith("        "):
                    expression_lines.append(stripped)
                else:
                    break
                i += 1

        # Now read metadata lines after the expression
        while i < len(lines):
            stripped = lines[i].strip()
            if stripped.startswith("lineageTag:"):
                i += 1
                continue
            elif stripped.startswith("formatString:"):
                format_string = stripped.split(":", 1)[1].strip()
                i += 1
                continue
            elif stripped.startswith("annotation "):
                i += 1
                continue
            elif stripped.startswith("changedProperty"):
                if "IsHidden" in stripped:
                    is_hidden = True
                i += 1
                continue
            elif stripped == "":
                i += 1
                continue
            else:
                break

        expression = "\n".join(expression_lines).strip()

        measures.append(MeasureInfo(
            name=name,
            table=table_name,
            expression=expression,
            format_string=format_string,
            is_hidden=is_hidden,
            file_path=str(file_path),
        ))

    return measures


def parse_tmdl_file(file_path):
    """Parse a single TMDL file and return a list of MeasureInfo."""
    path = Path(file_path)

    # Skip auto-generated files
    if any(path.stem.startswith(prefix) for prefix in _SKIP_PREFIXES):
        return []

    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return []

    lines = text.splitlines()
    table_name = _parse_table_name(lines)

    return _parse_measures(lines, table_name, file_path)


def discover_measures(model_path):
    """Walk all TMDL files in a SemanticModel and extract all measures.

    Args:
        model_path: path to the .SemanticModel folder (or its definition/tables/ subfolder)

    Returns: list of MeasureInfo
    """
    model_dir = Path(model_path)

    # Handle if user points to the SemanticModel root or directly to tables/
    tables_dir = model_dir / "definition" / "tables"
    if not tables_dir.exists():
        tables_dir = model_dir
        if not tables_dir.exists():
            raise FileNotFoundError(f"Cannot find tables directory at {model_path}")

    all_measures = []
    for tmdl_file in sorted(tables_dir.glob("*.tmdl")):
        measures = parse_tmdl_file(tmdl_file)
        all_measures.extend(measures)

    return all_measures
